# Generated by Django 5.1.3 on 2024-11-09 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_loginattempt"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="failed_attempts",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Неудачные попытки"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="is_blocked",
            field=models.BooleanField(default=False, verbose_name="Заблокирован"),
        ),
        migrations.DeleteModel(
            name="LoginAttempt",
        ),
    ]
