# Generated by Django 5.1.3 on 2024-11-11 12:16

import catalog.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_user_failed_attempts_user_is_blocked_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="выберите категорию", max_length=100),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=200, verbose_name="Напишите заголовок к заявке "
                    ),
                ),
                (
                    "description",
                    models.TextField(verbose_name="Напишите описание для заявки"),
                ),
                (
                    "image",
                    models.FileField(
                        upload_to="application",
                        validators=[catalog.models.validate_image],
                        verbose_name="Загрузите фото заявки",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "новая"),
                            ("active", "принято"),
                            ("done", "выполнено"),
                        ],
                        default="n",
                        help_text="статус заявки",
                        max_length=20,
                        verbose_name="статус заявки",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="дата и время создания"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.category",
                        verbose_name="Выберите категорию заявки",
                    ),
                ),
            ],
        ),
    ]
