# Generated by Django 5.1.3 on 2024-11-12 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_applicationhistory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "новая"),
                    ("active", "принято"),
                    ("done", "выполнено"),
                ],
                default="new",
                help_text="статус заявки",
                max_length=20,
                verbose_name="статус заявки",
            ),
        ),
    ]
